### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ice-cream567** [chensong1995/DeblurSR#3]
Hi, I think your work is great. Compared with other related literature, the production process of the data set is also very detailed. However, the production of the data set is very time-consuming. I would like to ask if it is possible to upload the generated raw data, that is, the unpreprocessed data before running create_hdf5_hr.py. This is convenient for everyone to develop. I would be grateful if you could.

**Comment by ice-cream567** [comment]
Hello, I encountered the following problems while trying to follow [REDS_Dataset.md](https://github.com/chensong1995/E-CIR/blob/main/REDS_Dataset.md) to generate rawdata for create_hdf5_hr.py:
When executing bash run_8x.sh in the third step, the following error occurs:
Traceback (most recent call last):

  File "run_8x.py", line 206, in <module>
    result[4] = estimate(left, right)
  File "run_8x.py", line 178, in estimate
    return torch.nn.functional.pad(input=netNetwork(tenPreprocessedOne, tenPreprocessedTwo), pad=[ 0 - intPaddingLeft, 0 - intPaddingRight, 0 - intPaddingTop, 0 - intPaddingBottom ], mode='replicate')[0, :, :, :].cpu()
  File "D:\anaconda3\envs\asd\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "run_8x.py", line 123, in forward
    tenDot1 = sepconv.FunctionSepconv(tenInput=tenOne, tenVertical=self.netVertical1(tenCombine), tenHorizontal=self.netHorizontal1(tenCombine))
AttributeError: module 'sepconv' has no attribute 'FunctionSepconv'

tenDot1 = sepconv.FunctionSepconv(tenInput=tenOne, tenVertical=self.netVertical1(tenCombine), tenHorizontal=self.netHorizontal1(tenCombine))
        tenDot2 = sepconv.FunctionSepconv(tenInput=tenTwo, tenVertical=self.netVertical2(tenCombine), tenHorizontal=self.netHorizontal2(tenCombine))

My analysis is because there is no function FunctionSepconv in [sepconv.py](https://github.com/sniklaus/sepconv-slomo/blob/master/sepconv.py).


Is it because the code is wrong or I made a mistake elsewhere? I hope you can reply.

**Comment by chensong1995** [comment]
Hi ice-cream567.

Thanks for your interest in our work! Unfortunately, the raw data is very big and we do not have sufficient space on the Internet to host the data. However, generating the data with the guide we provide should be straightforward.

I just took a look at the sepconv repository. It appears to me that some recent commits have modified the interface. My recommendation is to checkout commit `dae62e69e4708cd76cbde94963161fccc2f2c68b` ([link](https://github.com/sniklaus/sepconv-slomo/commit/dae62e69e4708cd76cbde94963161fccc2f2c68b)) and run the code again.

I hope this helps! Let me know if you have further questions.
